services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: idp
      POSTGRES_DB: idp
      POSTGRES_PASSWORD: idp
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  postgres:
