global:
  scrape_interval: 5s # Set the scrape interval. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every x seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "codelab-monitor"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
